---
title: "R Notebook"
output: html_notebook
---

-------------
title: Tarea5
-------------

```{r}
library(tidyverse)

answers <- read_csv('answers.csv')
question_tags <- read_csv('question_tags.csv')
questions <- read_csv('questions.csv')
tags <- read_csv('tags.csv')

```

<!-- 1. LEFT-JOINING -->
```{r}
questions_with_tags <- questions %>%
  left_join (question_tags, by=c("id" = "question_id")) %>%
  left_join (tags, by=c("tag_id" = "id")) %>%
  replace_na(list(tag_name='only-r'))

questions_with_tags

```

<!-- 2. COMPARING SCORES -->
```{r}
library(dplyr)

questions_with_tags %>%
  group_by(tag_name) %>%
  summarize(mean_score=mean(score)) %>%
  arrange(desc(mean_score))

```

<!-- 3. FINDING GAPS -->
```{r}
questions %>%
  inner_join (answers, by=c("id" = "question_id"), suffix=c("_question", "_answer")) %>%
  mutate (gap=creation_date_answer - creation_date_question)

```

<!-- 4. JOINING QUESTION AND ANSWER COUNTS-->
```{r}
answers_counts <- answers %>%
  count(question_id) %>%
  arrange(desc(n))

question_answers_counts <- questions %>%
  left_join(answers_counts, by=c("id" = "question_id")) %>%
  replace_na(list(n=0))

question_answers_counts

```
<!-- 5. JOINING QUESTION, ANSWERS AND TAGS -->
```{r}
question_tags %>%
  inner_join (question_answers_counts,by=c("question_id" = "id")) %>%
  inner_join (tags, by=c("tag_id" = "id")) %>%
  arrange(desc(n))

```

